# Generated by Django 3.2 on 2021-05-01 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=32, unique=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.product')),
            ],
            options={
                'unique_together': {('product_id', 'barcode')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('value', models.CharField(max_length=32)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.product')),
            ],
            options={
                'unique_together': {('product_id', 'name')},
            },
        ),
    ]
